// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtK4akJVJSOdRh5M8KYdkBsk0o3LjcbZQ',
    appId: '1:960480939653:android:17da574f67aec95849a3ec',
    messagingSenderId: '960480939653',
    projectId: 'agrobot-832c9',
    databaseURL: 'https://agrobot-832c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrobot-832c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpAqm0DF1Y-C3NM0Z1QkWP2FwoyU1q4dw',
    appId: '1:960480939653:ios:23ec7ca99bf4a9a249a3ec',
    messagingSenderId: '960480939653',
    projectId: 'agrobot-832c9',
    databaseURL: 'https://agrobot-832c9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agrobot-832c9.appspot.com',
    iosBundleId: 'com.example.agroapp',
  );
}
